name: Deploy site to Netlify
on:
  # schedule:
  # - cron: "30 8 * * *" # every evening at 11:30 PM
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-to-netlify:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v3"
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "projects/189812413207/locations/global/workloadIdentityPools/github/providers/github"
          service_account: "vakantieveilingen@lasse-benninga-sndbx-y.iam.gserviceaccount.com"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install evidence dependencies
        run: npm install

      - name: Generate sources
        run: npm run sources
        env:
          EVIDENCE_SOURCE__cloudsql__host: ${{ secrets.CLOUDSQL_HOST }}
          EVIDENCE_SOURCE__cloudsql__port: "5432"
          EVIDENCE_SOURCE__cloudsql__database: "vakantieveilingen"
          EVIDENCE_SOURCE__cloudsql__user: ${{ secrets.CLOUDSQL_USER }}
          EVIDENCE_SOURCE__cloudsql__password: ${{ secrets.CLOUDSQL_PASSWORD }}

      - name: Build evidence project
        run: npm run build

      - name: Deploy evidence build to Netlify
        uses: nwtgck/actions-netlify@v2.1
        with:
          publish-dir: "./build"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PAT }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE }}
        timeout-minutes: 30
